version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requirements_test.txt
      - pytest --pep8 --flakes  
  post_build:
    commands:
      - echo Build completed on `date`
